fix, ultimo commit
Msg de erro:
```
django.core.management.base.CommandError: One or more models did not validate:
journalmanager.section: "ordering" refers to "i", a field that doesn't exist.
journalmanager.section: "ordering" refers to "d", a field that doesn't exist.
```